//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OptoviySklad.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SkladMobileEntities : DbContext
    {
        public SkladMobileEntities()
            : base("name=SkladMobileEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Profile> Profile { get; set; }
        public DbSet<Sklad> Sklad { get; set; }
        public DbSet<Sklad_User> Sklad_User { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
