//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OptoviySklad.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sklad_User
    {
        public int id { get; set; }
        public Nullable<int> idTovar { get; set; }
    
        public virtual Sklad Sklad { get; set; }
    }
}
