//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OptoviySklad.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sklad
    {
        public Sklad()
        {
            this.Sklad_User = new HashSet<Sklad_User>();
        }
    
        public int id { get; set; }
        public string Tovar { get; set; }
        public string Price { get; set; }
        public byte[] Image { get; set; }
    
        public virtual ICollection<Sklad_User> Sklad_User { get; set; }
    }
}
